templates/python-flask/webapp1/models.py
from sqlalchemy import Table, Column, Integer, String
from sqlalchemy.orm import mapper
from flask_sqlalchemy import BaseQuery

from webapp1.database import metadata, db_session



class User(object):
  query = db_session.query_property(query_cls=BaseQuery)

  def __init__(self, username=None, password=None, email=None):
    self.username = username
    self.password = password
    self.email = email

  def __repr__(self):
    return f'<User {self.username!r}>'

users = Table('users', metadata,
  Column('id', Integer, nullable=False, primary_key=True),
  Column('username', String(48), nullable=False, unique=True),
  Column('password', String(48), nullable=False),
  Column('email', String(128), nullable=False, unique=True)
)
mapper(User, users)

templates/python-flask/webapp1/__init__.py
import os

from flask import Flask, render_template
from flask_mobility import Mobility


def create_app(test_config=None):
  app = Flask(__name__, instance_relative_config=True)
  app.config.from_mapping(
    SECRET_KEY="dev",
    #DATABASE=os.path.join(app.instance_path, "flaskr.sqlite"),
  )
  if test_config is None:
    app.config.from_pyfile("config.py", silent=True)
  else:
    app.config.update(test_config)

  try:
    os.makedirs(app.instance_path)
  except OSError:
    pass

  Mobility(app)

  from webapp1 import config
  app.app_config = config.init_application_properties()

  from webapp1 import database
  @app.teardown_appcontext
  def shutdown_session(exception=None):
    database.db_session.remove()

  from webapp1 import models

  from webapp1 import views
  app.register_blueprint(views.bp)
  
  from webapp1 import auth
  app.register_blueprint(auth.bp)

  app.add_url_rule("/", endpoint="views.index")

  return app

templates/python-flask/webapp1/auth.py
import functools
import subprocess

from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash
from sqlalchemy import text

from webapp1.database import db_session
from webapp1.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


def login_required(view):
  """View decorator that redirects anonymous users to the login page."""
  @functools.wraps(view)
  def wrapped_view(**kwargs):
    if g.user is None:
      return redirect(url_for("auth.login"))
    return view(**kwargs)
  return wrapped_view

@bp.before_app_request
def load_logged_in_user():
  """If a user id is stored in the session, load the user object from
  the database into ``g.user``."""
  user_id = session.get("user_id")
  if user_id is None:
    g.user = None
  else:
    g.user = User.query.filter_by(id=user_id).one()

def password_complexity_check(password):
  specialchars = ["!","@","#","$","%","^","&","*","(",")"]
  specialcharsfound = False
  tmppwd = password
  if len(tmppwd) <= 9:
    return False
  for x in specialchars:
    if tmppwd.find(x) > 0:
      specialcharsfound = True
      tmppwd = tmppwd.replace(x,"")
  if specialcharsfound == False:
    return False
  elif len(tmppwd) < 4:
    return False
  elif tmppwd.isalnum() == False:
    return False
  else:
    return True
  return False

@bp.route("/login", methods=("GET", "POST"))
def login():
  """Log in a registered user by adding the user id to the session."""
  if request.method == "POST":
    user_name = request.form["username"]
    pass_word = request.form["password"]
    error = None
    try:
      user = User.query.filter_by(username=user_name).one()
    except:
      user = None
    if user is None:
      error = "Incorrect username."
    elif not check_password_hash(user.password, pass_word):
      error = "Incorrect password."
    if error is None:
      # store the user id in a new session and return to the index
      session.clear()
      session["user_id"] = user.id
      return redirect(url_for("views.index"))
    flash(error)
    return redirect(url_for("auth.login"))
  return render_template("auth/login.html")

@bp.route("/logout")
def logout():
  """Clear the current session, including the stored user id."""
  session.clear()
  return redirect(url_for("views.index"))

templates/python-flask/webapp1/views.py
import functools

from flask import Blueprint, current_app, flash, g, redirect, render_template, request, session, url_for

#from webapp1.MODULE import bp as MODULE_bp


bp = Blueprint('views', __name__, url_prefix='/')
# bp.register_blueprint(MODULE_bp)


@bp.route('/')
def index():
  return render_template('index.html')

@bp.route('/test_1')
def test_1():
  return render_template('test1.html')

@bp.route('/test_2')
def test_2():
  return render_template('test2.html')

@bp.route('/test_3')
def test_3():
  return render_template('test3.html')

@bp.route('/test_4')
def test_4():
  return render_template('test4.html')

templates/python-flask/webapp1/templates/base.html
<!DOCTYPE html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>


<header>
  <ul>
    <li><a href="{{ url_for('views.index') }}">{% block header %}{% endblock %}</a></li>
    <li class="dropdown">
      <a href="javascript:void(0)" class="dropbtn">TEST</a>
      <div class="dropdown-content">
        <a href="{{ url_for('views.test_1') }}">TEST 1</a>
        <a href="{{ url_for('views.test_2') }}">TEST 2</a>
        <a href="{{ url_for('views.test_3') }}">TEST 3</a>
        <a href="{{ url_for('views.test_4') }}">TEST 4</a>
      </div>
    </li>
    {% block nav %}{% endblock %}
    {% if g.user %}
    <li><a href="{{ url_for('auth.logout') }}">{{ g.user.username }}</a></li>
    {% else %}
    <li><a href="{{ url_for('auth.login') }}">LOGIN</a></li>
    {% endif %}
  </ul>
</header>


<div class="row" style="margin-top:48px;">

<section class="bordered">
  <pre><code>MESSAGES:</code></pre>
</section>
{% for message in get_flashed_messages() %}
<section class="bordered">
  <pre><code>{{ message }}</code></pre>
</section>
{% endfor %}

<div class="content">
  {% block content %}{% endblock %}
</div>

</div>

<div style="height:48px;"></div>
<footer>
  {% block footer %}{% endblock %}
</footer>


</body>
</html>

templates/python-flask/webapp1/templates/index.html
{% extends 'base.html' %}


{% block title %}
TITLE
{% endblock %}


{% block header %}
HEADER
{% endblock %}


{% block content %}
<div class="content">
  <div class="bordered col-3 col-s-6">3</div><div class="bordered col-3 col-s-6">3</div>
  <div class="bordered col-3 col-s-6">3</div><div class="bordered col-3 col-s-6">3</div>
  <div class="bordered col-4 col-s-12">4</div><div class="bordered col-4 col-s-12">4</div><div class="bordered col-4 col-s-12">4</div>
  <div class="bordered col-6 col-s-12">6</div><div class="bordered col-6 col-s-12">6</div>
  <div class="bordered col-12 col-s-12">12</div>
</div>

<div class="content">
  <form action="">
   <fieldset><legend>Form Items</legend>
    <div class="col-6 col-s-12"><fieldset><legend>Fields 1</legend>
      <label for="test-text">Text</label>
      <input type="text" id="test-text" name="test-text" value="" placeholder="Text Input">
      <label for="test-password">Password</label>
      <input type="password" id="test-password" name="test-password" value="" placeholder="Password Input">
      <label for="test-email">Email</label>
      <input type="email" id="test-email" name="test-email" value="" placeholder="Email">
      <label for="test-tel">Telephone</label>
      <input type="tel" id="test-tel" name="test-tel" value="" placeholder="Telephone">
      <label for="test-url">URL</label>
      <input type="url" id="test-url" name="test-url" value="" placeholder="URL">
      <label for="test-num">Integer</label>
      <input type="number" id="test-num" name="test-num" value="" placeholder="Integer Number">
      <label for="test-range">Range</label>
      <input type="range" id="test-range" name="test-range" min="10" max="90" step="5" value="">
      <label for="test-search">Search</label>
      <input type="search" id="test-search" name="test-search" value="" placeholder="Search term">
    </fieldset></div>

    <div class="col-6 col-s-12"><fieldset><legend>Fields 2</legend>
      <label for="test-datetime">Datetime-Local</label>
      <input type="datetime-local" id="test-datetime" name="test-datetime" value="">
      <label for="test-date">Date</label>
      <input type="date" id="test-date" name="test-date" value="">
      <label for="test-month">Month</label>
      <input type="month" id="test-month" name="test-month" value="">
      <label for="test-week">Week</label>
      <input type="week" id="test-week" name="test-week" value="">
      <label for="test-time">Time</label>
      <input type="time" id="test-time" name="test-time" value="">
    </fieldset></div>

    <div class="col-6 col-s-12"><fieldset><legend>Select Field</legend>
      <select id="test-select" name="test-select" value="">
        <option value="" selected disbled>Select an Option</option>
        <optgroup label="GROUP 1">
          <option value="">A</option>
          <option value="">B</option>
          <option value="">C</option>
        </optgroup>
        <optgroup label="GROUP 2">
          <option value="">a</option>
          <option value="">b</option>
          <option value="">c</option>
        </optgroup>
      </select>
    </fieldset></div>

    <div class="col-6 col-s-12"><fieldset><legend>Radios and Check Boxes</legend>
      <div class="col-6 col-s-12">
        <input type="radio" id="test-radio-1" name="test-radio-value" value="">
        <label for="test-radio-1">Radio 1</label><br>
        <input type="radio" id="test-radio-2" name="test-radio-value" value="">
        <label for="test-radio-2">Radio 2</label><br>
        <input type="radio" id="test-radio-3" name="test-radio-value" value="">
        <label for="test-radio-3">Radio 3</label>
      </div>
      <div class="col-6 col-s-12">
        <input type="checkbox" id="test-check-1" name="test-check-1" value="">
        <label for="test-check-1">Check 1</label><br>
        <input type="checkbox" id="test-check-2" name="test-check-2" value="">
        <label for="test-check-2">Check 2</label><br>
        <input type="checkbox" id="test-check-3" name="test-check-3" value="">
        <label for="test-check-3">Check 3</label>
      </div>
    </fieldset></div>

    <div class="col-6 col-s-12"><fieldset><legend>Fields</legend>
      <input type="color" id="test-color" name="test-color" value="">
      <input type="image" id="test-img" name="test-img" value="">
      <input type="file" id="test-file" name="test-file" value="">
    </fieldset></div>

    <div class="col-12 col-s-12">
      <textarea id="test-textarea" name="test-textarea" value="" placeholder="Text area" rows="3"></textarea>
      <input type="button" onclick="alert('Hello World!')" value="Button JS Alert">
    </div>

    <div class="col-12 col-s-12">
      <input type="submit" value="SUBMIT">
      <input type="reset">
    </div>
   </fieldset>
  </form>
</div>

<div class="content">
  <table>
    <tr>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
      <th>E</th>
    </tr>
    <tr>  
      <td>@</td>
      <td>#</td>
      <td>$</td>
      <td>%</td>
      <td>&</td>
    </tr>
    <tr>
      <td>@</td>
      <td>#</td>
      <td>$</td>
      <td>%</td>
      <td>&</td>
    </tr>
    <tr>  
      <td>@</td>
      <td>#</td>
      <td>$</td>
      <td>%</td>
      <td>&</td>
    </tr>
    <tr>
      <td>@</td>
      <td>#</td>
      <td>$</td>
      <td>%</td>
      <td>&</td>
    </tr>
    <tr>  
      <td>@</td>
      <td>#</td>
      <td>$</td>
      <td>%</td>
      <td>&</td>
    </tr>
    <tr>
      <td>@</td>
      <td>#</td>
      <td>$</td>
      <td>%</td>
      <td>&</td>
    </tr>
  </table>
</div>

<div class="content">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>
{% endblock %}


{% block footer %}
<div class="content">
  <a href="{{ url_for('views.index') }}">FOOTER</a>
</div>
{% endblock %}

templates/python-flask/webapp1/templates/test1.html
{% extends 'base.html' %}


{% block title %}
TEST - 1
{% endblock %}


{% block header %}
TEST - Containers
{% endblock %}

{% block nav %}
{% endblock %}


{% block content %}
<div class="content flex-container">
  <div class="content bordered">
    <table>
      <tr><th><a href="{{ url_for('views.test_3') }}">HOSTNAME</a></th></tr>
      <tr><td>
        <a href="ssh://127.0.0.1/" class="button">SSH</a>
        <a href="http://127.0.0.1/" target="_blank">127.0.0.1</a>
        </td></tr>
      <tr><td>GROUP</td></tr>
      <tr><td># CPU / # GB RAM</td></tr>
      <tr><td><div style="max-width:512px;overflow:auto;">NOTES</div></td></tr>
    </table>
  </div>
  
  <div class="content bordered">
    <table>
      <tr><th><a href="">Very-Long-Hostnameeeeeeeeeeeee</a></th></tr>
      <tr><td>
        <a href="ssh://127.0.0.1/" class="button">SSH</a>
        <a href="">230.255.255.254</a>
        </td></tr>
      <tr><td>LONG GROUP NAMEEEEEEEEEE</td></tr>
      <tr><td>64 CPU / 999 GB RAM</td></tr>
      <tr><td><div style="max-width:512px;overflow:auto;">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </div></td></tr>
    </table>
  </div>
  <div class="content bordered">
    <table>
      <tr><th><a href="">HOSTNAME</a></th></tr>
      <tr><td>
        <a href="ssh://127.0.0.1/" class="button">SSH</a>
        <a href="http://127.0.0.1/" target="_blank">127.0.0.1</a>
        </td></tr>
      <tr><td>GROUP</td></tr>
      <tr><td># CPU / # GB RAM</td></tr>
      <tr><td><div style="max-width:512px;overflow:auto;">NOTES</div></td></tr>
    </table>
  </div>
  <div class="content bordered">
    <table>
      <tr><th><a href="">Very-Long-Hostnameeeeeeeeeeeee</a></th></tr>
      <tr><td>
        <a href="ssh://127.0.0.1/" class="button">SSH</a>
        <a href="">230.255.255.254</a>
        </td></tr>
      <tr><td>LONG GROUP NAMEEEEEEEEEE</td></tr>
      <tr><td>64 CPU / 999 GB RAM</td></tr>
      <tr><td><div style="max-width:512px;overflow:auto;">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </div></td></tr>
    </table>
  </div>
  <div class="content bordered">
    <table>
      <tr><th><a href="">Very-Long-Hostnameeeeeeeeeeeee</a></th></tr>
      <tr><td>
        <a href="ssh://127.0.0.1/" class="button">SSH</a>
        <a href="">230.255.255.254</a>
        </td></tr>
      <tr><td>LONG GROUP NAMEEEEEEEEEE</td></tr>
      <tr><td>64 CPU / 999 GB RAM</td></tr>
      <tr><td><div style="max-width:512px;overflow:auto;">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </div></td></tr>
    </table>
  </div>
  <div class="content bordered">
    <table>
      <tr><th><a href="">HOSTNAME</a></th></tr>
      <tr><td>
        <a href="ssh://127.0.0.1/" class="button">SSH</a>
        <a href="http://127.0.0.1/" target="_blank">127.0.0.1</a>
        </td></tr>
      <tr><td>GROUP</td></tr>
      <tr><td># CPU / # GB RAM</td></tr>
      <tr><td><div style="max-width:512px;overflow:auto;">NOTES</div></td></tr>
    </table>
  </div>
  <div class="content bordered">
    <table>
      <tr><th><a href="">HOSTNAME</a></th></tr>
      <tr><td>
        <a href="ssh://127.0.0.1/" class="button">SSH</a>
        <a href="http://127.0.0.1/" target="_blank">127.0.0.1</a>
        </td></tr>
      <tr><td>GROUP</td></tr>
      <tr><td># CPU / # GB RAM</td></tr>
      <tr><td><div style="max-width:512px;overflow:auto;">NOTES</div></td></tr>
    </table>
  </div>
  <div class="content bordered">
    <table>
      <tr><th><a href="">HOSTNAME</a></th></tr>
      <tr><td>
        <a href="ssh://127.0.0.1/" class="button">SSH</a>
        <a href="http://127.0.0.1/" target="_blank">127.0.0.1</a>
        </td></tr>
      <tr><td>GROUP</td></tr>
      <tr><td># CPU / # GB RAM</td></tr>
      <tr><td><div style="max-width:512px;overflow:auto;">NOTES</div></td></tr>
    </table>
  </div>
  <div class="content bordered">
    <table>
      <tr><th><a href="">Very-Long-Hostnameeeeeeeeeeeee</a></th></tr>
      <tr><td>
        <a href="ssh://127.0.0.1/" class="button">SSH</a>
        <a href="">230.255.255.254</a>
        </td></tr>
      <tr><td>LONG GROUP NAMEEEEEEEEEE</td></tr>
      <tr><td>64 CPU / 999 GB RAM</td></tr>
      <tr><td><div style="max-width:512px;overflow:auto;">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </div></td></tr>
    </table>
  </div>
  <div class="content bordered">
    <table>
      <tr><th><a href="">Very-Long-Hostnameeeeeeeeeeeee</a></th></tr>
      <tr><td>
        <a href="ssh://127.0.0.1/" class="button">SSH</a>
        <a href="">230.255.255.254</a>
        </td></tr>
      <tr><td>LONG GROUP NAMEEEEEEEEEE</td></tr>
      <tr><td>64 CPU / 999 GB RAM</td></tr>
      <tr><td><div style="max-width:512px;overflow:auto;">
        </div></td></tr>
    </table>
  </div>
  <div class="content bordered">
    <table>
      <tr><th><a href="">HOSTNAME</a></th></tr>
      <tr><td>
        <a href="ssh://127.0.0.1/" class="button">SSH</a>
        <a href="http://127.0.0.1/" target="_blank">127.0.0.1</a>
        </td></tr>
      <tr><td>GROUP</td></tr>
      <tr><td># CPU / # GB RAM</td></tr>
      <tr><td><div style="max-width:512px;overflow:auto;">NOTES</div></td></tr>
    </table>
  </div>
  <div class="content bordered">
    <table>
      <tr><th><a href="">HOSTNAME</a></th></tr>
      <tr><td>
        <a href="ssh://127.0.0.1/" class="button">SSH</a>
        <a href="http://127.0.0.1/" target="_blank">127.0.0.1</a>
        </td></tr>
      <tr><td>GROUP</td></tr>
      <tr><td># CPU / # GB RAM</td></tr>
      <tr><td><div style="max-width:512px;overflow:auto;">NOTES</div></td></tr>
    </table>
  </div>
</div>


{% endblock %}


{% block footer %}
{% endblock %}

templates/python-flask/webapp1/templates/test2.html
{% extends 'base.html' %}


{% block title %}
TEST - 1
{% endblock %}


{% block header %}
TEST - Form
{% endblock %}

{% block nav %}
{% endblock %}


{% block content %}
<div class="content">
  <h1>Create System</h1>
</div>
<div class="content flex-container">
  <form>
    <fieldset class="content col-5 col-s-12"><legend>Connection Settings</legend>
      <label for="hostname">Hostname</label>
      <input type="text" id="hostname" name="hostname" placeholder="Hostname" required>
      
      <label for="ipaddress">IP Address</label>
      <input type="text" id="ipaddress" name="ipaddress" placeholder="IP Address" required>
      
      <div class="content bordered">
        <label for="sshpubkey">SSH Public Key for Host Connection</label>
        <input type="file" id="sshpubkey" name="sshpubkey">
        <br>
        
        <input type="checkbox" id="userlogin" name="userlogin" value="userlogin">
        <label for="userlogin">Username/Password Login</label>
        <br>
        
        <label for="username">Username</label>
        <input type="text" id="username" name="username" placeholder="Username" autocomplete=off required>
        
        <label for="password">Password</label>
        <input type="password" id="password" name="password" placeholder="Password" required>
      </div>
      
      <label for="category">Category</label>
      <select id="category" name="category">
        <option selected disabled>Select an option</option>
        <optgroup label="Bare Metal">
          <option value="Desktop">Desktop</option>
          <option value="Laptop">Laptop</option>
          <option value="Server">Server</option>
          <option value="Hypervisor">Hypervisor</option>
        </optgroup>
        <optgroup label="Cloud Hosted">
          <option value="AWSec2">AWS EC2</option>
          <option value="GCPcompute">GCP Compute</option>
          <option value="AzureCompute">Azure Compute</option>
          <option value="CloudOther">Other Cloud</option>
        </optgroup>
        <optgroup label="Virtual">
          <option value="VM">VM</option>
          <option value="ContainerDocker">Container - Docker</option>
          <option value="ContainerK8S">Container - Kubernetes</option>
          <option value="ContainerLXC">Container - LXC</option>
        </optgroup>
        <optgroup label="Mobile">
          <option value="TabletApple">Tablet - Apple</option>
          <option value="TabletAndroid">Tablet - Android</option>
          <option value="TabletOther">Tablet - Other</option>
          <option value="CellPhoneApple">Cell Phone - Apple</option>
          <option value="CellPhoneAndroid">Cell Phone - Android</option>
          <option value="CellPhoneOther">Cell Phone - Other</option>
          <option value="MobileOther">Mobile - Other</option>
        </optgroup>
        <optgroup label="IOT">
          <option value="SmartTV">Smart TV</option>
          <option value="Router">Router</option>
          <option value="IOTOther">IOT - Other</option>
        </optgroup>
        <option value="other">Other</option>
      </select>
      <input type="text" id="categoryother" name="categoryother" placeholder="Description for Other option">
      
      <label for="group">Category</label>
      <select id="group" name="group">
        <option selected disabled>Select an option</option>
        <option value="GroupA">Group A</option>
        <option value="GroupB">Group B</option>
        <option value="GroupC">Group C</option>
        <option value="other">Other</option>
      </select>
    </fieldset>
    
    <fieldset class="content col-5 col-s-12"><legend>System Configuration</legend>
      <div class="content">
        <label>CPU Type</label>
        <br>
        <input type="radio" id="intel" name="cputype" value="Intel">
        <label for="x86">x86</label><br>
        <input type="radio" id="amd" name="cputype" value="AMD">
        <label for="amd64">amd64</label><br>
        <input type="radio" id="other" name="cputype" value="Other">
        <label for="armhf">armhf</label>
      </div>
      
      <label for="cpucores">Cores</label>
      <input type="number" id="cpucores" name="cpucores">
      
      <label for="memory">Memory</label>
      <input type="text" id="memory" name="memory" placeholder="Memory in GB">
      
      <label for="disknumber">Number of Disks</label>
      <input type="number" id="disknumber" name="disknumber">
      
      <label for="disksize">Primary Disk Size</label>
      <input type="text" id="disksize" name="disksize" placeholder="Disk Size in GB">
      
      <div class="content bordered">
        <label>Architecture</label>
        <br>
        <input type="radio" id="x8664" name="cpuarch" value="x8664">
        <label for="x8664">x86/64</label><br>
        <input type="radio" id="amd64" name="cpuarch" value="amd64">
        <label for="amd64">amd64</label><br>
        <input type="radio" id="armhf" name="cpuarch" value="armhf">
        <label for="armhf">armhf</label>
        <input type="radio" id="arm64" name="cpuarch" value="arm64">
        <label for="arm64">arm64</label>
      </div>
      
      <label for="os">Operating System</label>
      <select id="os" name="os">
        <option selected disabled>Select an option</option>
        <optgroup label="Linux">
          <option value="Ubuntu">Ubuntu</option>
          <option value="Debian">Debian</option>
          <option value="CentOS">CentOS</option>
          <option value="RHEL">RHEL</option>
          <option value="AlpineLinux">Alpine Linux</option>
          <option value="OtherLinux">Other Linux</option>
        </optgroup>
        <optgroup label="Windows">
          <option value="Windows1011">Windows 10/11</option>
          <option value="WindowsServer1619">Windows Server 2016/19</option>
          <option value="WindowsServer2012">Windows Server 2012</option>
        </optgroup>
        <optgroup label="macOS">
          <option value="macOS">macOS</option>
        </optgroup>
        <optgroup label="Mobile">
          <option value="iOS">iOS</option>
          <option value="Android">Android</option>
        </optgroup>
        <option value="CiscoIOS">Cisco IOS</option>
        <option value="other">Other</option>
      </select>
      
      <div class="container">
        <textarea id="description" name="description" rows="10" placeholder="Enter a description or any notes for this system"></textarea>
      </div>
      
      <input type="submit" value="SUBMIT">
      <input type="reset">
    </fieldset>
  </form>
</div>


{% endblock %}


{% block footer %}
{% endblock %}